# Generated by Django 5.0.4 on 2024-05-07 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество просмотров"
            ),
        ),
    ]
