# Generated by Django 5.0.4 on 2024-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="текущая версия"),
        ),
    ]
