# Generated by Django 5.0.4 on 2024-05-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_version_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
    ]
